language: scala
branches:
  except:
  - release
  - website
script:
- "./build/build.sh"
after_success:
- pip install --user codecov && codecov
sudo: true
env:
  global:
    secure: AbRIm4jQ7gzspIwWQ2Rm7fM52nafaVIgPZZtplhd0NlkGDiJssJY+FOhnvv9mv7MMnxkpQfjjIMJnSsvXprqtK/EER8mYRt/HYJW0U4u8xPKjKQTi1xgATMo7hhdMnAWmBQO+PbDtAM+30KdiO9k3fA8vCd/A/AWkwEHXsJ6YVZLDUcEDdr2N0jbGDluGvcdgItb86CbjXus7j2jVBNydMvLkcPxM1XsQfuRdNi5eUuS7sLlb/rYKbh5CLDX+AQ6IplsFceatUyS8FazaqpQhCUxc/Eovfi05T9i7imtQy15YyqEpnEYIWc+WmHZ1ebwunZZNj3+kzoQkE/Euam0u3X0I1S+9trNM5wcEBcSLUB2MJ634c8mspWNj3G2oDlT9F0rcmati51JqpFwwxM8s7a2EA23fakpZPhwSD/G7nEj3a3Pfgb+sEIhtJzHcICg5vrmNZgYReVcsMS0eylAQ7nphPD8xo82v8mhADg6lKX4LhpQF76CBSt+R9PkzYhcW+3xh2rvHIUephf6z8d1TuGdJwx/4ZLjE5RhsMjT80cdQovbNlp5dW9xZ6s0wsDxubuEYfDbxy0rjRHkH5OTsj6uUbM5Cd/dqkTuKxwkEOaU3Up5azYtFMYq+b62J1pvGzrgguieIWzbRWWDgNwTwp4RfJLh0urNIVrr55Z+RQw=
